# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: soh-site-prod
  labels:
    app: soh-site-prod
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  type: ClusterIP
  selector:
    app: soh-site-prod
