# Kubernetes
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: soh-site-prod-v0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: soh-site-prod
        version: v0
    spec:
      volumes:
        - name: secret
          secret:
            secretName: soh-site-prod
      containers:
        - name: rdr2tls
          image: dysinger/rdr2tls:0.1.1
          command:
            - rdr2tls
            - --port
            - "8080"
          ports:
            - name: http
              containerPort: 8080
        - name: soh-site
          image: fpco/soh-site:latest
          imagePullPolicy: Always
          env:
            - name: FP_ENVIRONMENT_NAME
              value: production
            - name: FP_ENVIRONMENT_TYPE
              value: production
            - name: FP_DEPLOYMENT_TYPE
              value: aws
            - name: BLOB_STORE_SETTINGS
              value: /config/blob-store-production.yaml
            - name: LEARNING_SITE_PGPOOLSIZE
              value: "100"
            - name: LEARNING_SITE_MAIL_FROM
              value: noreply@schoolofhaskell.com
            - name: LEARNING_SITE_BIND
              value: "*4"
            - name: LEARNING_SITE_PORT
              value: "8443"
            - name: LEARNING_SITE_APPROOT
              value: https://www.schoolofhaskell.com
          volumeMounts:
            - name: secret
              readOnly: true
              mountPath: /etc/secret
          command:
            - sh
            - -c
              # This loads environment variables from secrets before launching
            - rm -f /config/client_session_key.aes;
              ln -s /etc/secret/client-session-key.aes /config/client_session_key.aes;
              eval "$(for x in /etc/secret/env-*; do echo "export $(basename "$x"|sed 's/^env-//'|tr 'a-z-' 'A-Z_')=\"$(cat $x)\";" ; done)";
              exec soh-site
          ports:
            - name: https
              containerPort: 8443
