# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: soh-site
  labels:
    app: soh-site
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: soh-site
  type: LoadBalancer
