# Kubernetes
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: soh-site
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: soh-site
    spec:
      containers:
      - name: rdr2tls
        image: dysinger/rdr2tls:0.1.1
        command:
        - rdr2tls
        - --port
        - "8080"
        ports:
        - name: http
          containerPort: 8080
      - name: soh-site
        image: fpco/soh-site:latest
        env:
          - name: FP_ENVIRONMENT_NAME
            value: production
          - name: FP_ENVIRONMENT_TYPE
            value: production
          - name: FP_DEPLOYMENT_TYPE
            value: aws
          - name: BLOB_STORE_SETTINGS
            value: /config/blob-store-production.yaml
          - name: LEARNING_SITE_PGCONNSTR
            value: dbname=learning_site host=localhost user=learning_site password=learning-site port=5432
          - name: LEARNING_SITE_PGPOOLSIZE
            value: "100"
          - name: LEARNING_SITE_MAIL_FROM
            value: noreply@schoolofhaskell.com
          - name: LEARNING_SITE_ANALYTICS
            value: UA-36928035-1
          - name: LEARNING_SITE_BIND
            value: "*4"
          - name: LEARNING_SITE_PORT
            value: "8443"
          - name: LEARNING_SITE_APPROOT
            value: https://www.schoolofhaskell.com
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: "PUT_CLIENT_ID_HERE"
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            value: "PUT_CLIENT_SECRET_HERE"
          - name: AWS_ACCESS_KEY
            value: "PUT_ACCESS_KEY_HERE"
          - name: AWS_SECRET_KEY
            value: "PUT_SECRET_KEY_HERE"
        command:
        - soh-site
        ports:
        - name: https
          containerPort: 8443
