# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: soh-site
  labels:
    app: soh-site
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: soh-site
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: soh-site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: soh-site
    spec:
      containers:
      - name: rdr2tls
        image: dysinger/rdr2tls:0.1.1
        command:
        - rdr2tls
        - --port
        - "8080"
        ports:
        - name: http
          containerPort: 8080
        restartStrategy: always
      - name: soh-site
        image: fpco/soh-site:latest
        env:
          - name: FP_ENVIRONMENT_NAME
            value: production
          - name: FP_ENVIRONMENT_TYPE
            value: production
          - name: FP_DEPLOYMENT_TYPE
            value: aws
          - name: BLOB_STORE_SETTINGS
            value: /config/blob-store-production.yaml
          - name: LEARNING_SITE_PGCONNSTR
            value: dbname=learning_site host=localhost user=learning_site password=learning-site port=5432
          - name: LEARNING_SITE_PGPOOLSIZE
            value: "100"
          - name: LEARNING_SITE_MAIL_FROM
            value: noreply@schoolofhaskell.com
          - name: LEARNING_SITE_ANALYTICS
            value: UA-36928035-1
          - name: LEARNING_SITE_BIND
            value: "*4"
          - name: LEARNING_SITE_PORT
            value: "80"
          - name: LEARNING_SITE_APPROOT
            value: https://www.schoolofhaskell.com
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: "219123459670-s2a0rs5tjptqol2oo3f0u27ac6it9riv.apps.googleusercontent.com"
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            value: "VPosg0Tt04Bwv8Hj-U3L6fhN"
          - name: AWS_ACCESS_KEY
            value: "PUT_ACCESS_KEY_HERE"
          - name: AWS_SECRET_KEY
            value: "PUT_SECRET_KEY_HERE"
        command:
        - soh-site
        ports:
        - name: https
          containerPort: 8443
        restartStrategy: always
